### ISSUE TITLE
Downloading plugin repeatedly times out

### ISSUE THREAD

**Issue by psfblair** [Frege/eclipse-plugin#10]
I've had this problem repeatedly when trying to install frege.ide_3.23.200.a using Eclipse, from different (fast) networks. Installation starts and when reaching "Fetching frege.ide_3.23.200.a.jar from (site)" generally pauses between 0.5 and 2 MB from the full download size. Eventually the download times out.

I am ultimately able to install if I try several times.

**Comment by Ingo60** [comment]
Sorry to hear this.
I never experienced this, but last time I tried eclipse told me that there was no repository.
So I tried with this path

> https://raw.githubusercontent.com/Frege/frege.github.com/master/fregide

and it did work much better. Perhaps this would also help in your case?

**Comment by psfblair** [comment]
Yes, this URL worked much better. Thanks!

**Comment by Ingo60** [comment]
Glad there is a workaround.

I'm not always happy with the file serving by github, recently. Anyway, I'll put the link above to the wiki page as a possible alternative for the case that things are not working as expected (they definitly did work for a long time until some weeks ago, maybe it has to do with the chinese attack?).

**Comment by ser10us** [comment]
Neither of these links is working in Eclipse neon.1. The download just stops at 6 Mb.
