### ISSUE TITLE
error building frege project

### ISSUE THREAD

**Issue by santifa** [Frege/eclipse-plugin#11]
Hi folks, 
I tried Frege with the Eclipse IDE Plugin, but the compilation failed.
I get the following error message:

    Errors occurred during the build.
    Errors running builder 'Frege builder' on project 'frege-test'.
    Could not initialize class frege.compiler.common.CompilerOptions

I'm using Eclipse Luna Service Release 2 (4.4.2) 

Any Suggestions to this problem?
Many thanks in advance!

**Comment by Ingo60** [comment]
Hmmm ... this is hard to tell, indeed. It should work out of the box. I need to ask some questions.

Is this the latest plugin version? (3.23.200.a)
Is this the only version you did install?

Is the fregec.jar in the build path and listed under "Referenced Libraries"? If yes, what is the size of that file? Can you use it to compile from the command line?

Can you edit a frege source file? Do you get syntax coloring, live error markers etc.?

Are you running Windows or Unix-like? In the latter case, please start luna from a terminal session and post the messages that appear there.

I also can check Luna 4.4.2, until now I have only used it with 4.4.1. OTOH one wouldn't expect groundbreaking changes with a service release?

**Comment by santifa** [comment]
Ok.. I forgot, I get another failure on creating a new *.fr file too.

    Errors occurred during the build.
    Errors running builder 'Frege builder' on project 'frege-test'.
    frege/runtime/Fun2 : Unsupported major.minor version 52.0

This error is prepended by another error message "Failed to instantiate parser..."

I've installed the latest plugin version 3.23.200.a and this is the only frege plugin installed.
There is no autocompletion, syntax highlighting etc.

The fregec.jar file is about 25 megabytes and is referenced in the eclipse project.
If I try to compile *.fr files from command line I get the following error message which is similiar the the one from eclipse.

    Exception in thread "main" java.lang.UnsupportedClassVersionError: frege/runtime/Fun1 :   Unsupported major.minor version 52.0
    And the usual Java classloader stack trace

I'm using Arch Linux. The consoleLog and debug output is the following when the first error occurs.

Start VM: /usr/bin/java
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms400m
-Xmx1024m
-Xss4m
-jar /usr/share/eclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
-os linux
-ws gtk
-arch x86_64
-showsplash /usr/share/eclipse//plugins/org.eclipse.platform_4.4.2.v20150204-1700/splash.bmp
-launcher /usr/share/eclipse/eclipse
-name Eclipse
--launcher.library /usr/share/eclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.200.v20150204-1316/eclipse_1607.so
-startup /usr/share/eclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
--launcher.appendVmargs
-exitdata 420001
-product org.eclipse.epp.package.standard.product
-consoleLog
-debug
-vm /usr/bin/java
-vmargs
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms400m
-Xmx1024m
-Xss4m
-jar /usr/share/eclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar 
Install location:
    file:/usr/share/eclipse/
Configuration file:
    file:/usr/share/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/ratzeputz/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/
Configuration file:
    file:/home/ratzeputz/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/config.ini loaded
Loading timestamp file from:
	 file:/home/ratzeputz/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp
Timestamps found: 
	 config.ini in the base: 1424336656000
	 remembered 1424336656000
Shared configuration location:
    file:/usr/share/eclipse/configuration/
Framework located:
    file:/usr/share/eclipse/plugins/org.eclipse.osgi_3.10.2.v20150203-1939.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.1.v20140709-1414.jar
	eclipse.properties not found
Loading extension: reference:file:../../../../home/ratzeputz/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/plugins/org.eclipse.equinox.weaving.hook_1.1.100.weaving-hook-20140821.jar
	eclipse.properties not found
Framework classpath:
    file:/usr/share/eclipse/plugins/org.eclipse.osgi_3.10.2.v20150203-1939.jar
    file:/usr/share/eclipse/plugins/
    file:/usr/share/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.1.v20140709-1414.jar
    file:/usr/share/eclipse/plugins/../../../../home/ratzeputz/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/plugins/org.eclipse.equinox.weaving.hook_1.1.100.weaving-hook-20140821.jar
Splash location:
    /usr/share/eclipse//plugins/org.eclipse.platform_4.4.2.v20150204-1700/splash.bmp
Debug options:
    file:/home/ratzeputz/.options not found
Time to load bundles: 21
Starting application: 3179
!SESSION 2015-06-12 13:13:14.623 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.standard.product -consoleLog -debug

!ENTRY org.eclipse.jface 2 0 2015-06-12 13:13:34.075
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-06-12 13:13:34.075
!MESSAGE A conflict occurred for CTRL+F4:
Binding(CTRL+F4,
	ParameterizedCommand(Command(org.eclipse.ui.file.close,Close,
		Close the active editor,
		Category(org.eclipse.ui.category.file,File,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@57fa107b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+F4,
	ParameterizedCommand(Command(org.scala.tools.eclipse.search.commands.OpenTypeHierarchy,Open Type Hierarchy,
		Open Type Hierarchy,
		Category(org.scala.tools.eclipse.search.commands,Search - Scala,Search - Scala,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6250285c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Application Started: 29662

I see nothing interesting there and all other plugins work just fine.
No I don't expect groundbreaking changes but with eclipse there is always some magic that seems to hold the whole system consistent.

**Comment by Ingo60** [comment]
Ok, then the case is clear.
Looks like I accidentally compiled this with java8, and this cannot be consumed by Java7.

I shall upload a Java7 compatible version this weekend, however, you may simply install a JDK 8 and run your Luna with it to fix this.

**Comment by Ingo60** [comment]
I've uploaded frege.ide-3.23.246.aq

Please try whether it works in your setting.

BTW, thank you for reporting, obviously many people use already JVM8 so it could go unnoticed for a while ....

**Comment by santifa** [comment]
I tried the new version and everything works as expected.
No problem and thanks for the quick help.
