### ISSUE TITLE
=> vs -> in type popup

### ISSUE THREAD

**Issue by Dierk** [Frege/eclipse-plugin#12]
when hovering over a reference the type is shown.
At least in eclipse mars, this comes up as e.g.

>  liftMx :: Monad m -> (a -> b) -> m a -> m b

whereas in the outline view it is correctly displayed as

> liftMx :: Monad m => (a -> b) -> m a ->  m b

**Comment by Ingo60** [comment]
Luna here.
Looks like this is so when you turn off "Use Unicode Symbols" while it is correct in UniCode.
I wonder what crap I programmed there, will look into it.

(When changing this property, it will be in effect only in new Editor instances, not in still open ones.)

**Comment by Dierk** [comment]
ok, makes sense. I am now using unicode symbols ;-)

**Comment by Ingo60** [comment]
Since this is not eclipse-specific, I am closing this issue, the case is handled in https://github.com/Frege/frege/issues/153
