### ISSUE TITLE
handling of "package"

### ISSUE THREAD

**Issue by Dierk** [Frege/eclipse-plugin#13]
It appears that the eclipse plugin takes issue with  the "package" keyword as used in the Maybe module. Since the build is running through otherwise, I assume this signals a "false positive" (?)
![bildschirmfoto 2015-06-26 um 15 59 14](https://cloud.githubusercontent.com/assets/51843/8378880/b0ffc0ce-1c1c-11e5-85cb-432179266a8d.png)

**Comment by Ingo60** [comment]
There should be some message when you hover over the error marker?

Is this just the result of some "Go To Definition" or are you working with the frege project sources in eclipse?

**Comment by Dierk** [comment]
I couldn't make that work but no big deal.

**Comment by Dierk** [comment]
after some restarts, it seems to have gone (?) ...

**Comment by Dierk** [comment]
and there it is again...

Multiple messages at this line.
	- _constƒ5f186b3d cannot be resolved or is not a field
	- Java compiler errors are almost always caused by bad native declarations. When you're sure this is out 
	 of the question you've found a compiler bug, please report under https://github.com/frege/frege/issues and 
	 attach a copy of /projects/git/frege/bin/frege/prelude/Maybe.java
	- _constƒ5f186b3d cannot be resolved or is not a field

**Comment by Ingo60** [comment]
That is definitely a class path problem. 
Did you follow my advise concerning the prefix?

**Comment by Dierk** [comment]
Yes, but that almost broke my whole installation. It seems that eclipse is totally unpredictable when it comes to when and how it picks up new settings and recompiles (and I always thought this would be the basic task of IDEs)

**Comment by Dierk** [comment]
Hm, I disabled "build automatically" and now it builds automatically (but works). Let's see for how long.
