### ISSUE TITLE
Workspace error in MARS.1

### ISSUE THREAD

**Issue by muhuk** [Frege/eclipse-plugin#15]
Errors occurred during the build.
    Error instantiating builder 'frege.ide.frege.builder'.
    Plug-in "frege.ide" was unable to instantiate class "frege.imp.builders.FregeBuilder".
    org.eclipse.ui.internal.registry.FileEditorMapping.setDefaultEditor(Lorg/eclipse/ui/internal/registry/EditorDescriptor;)V
    Plug-in "frege.ide" was unable to instantiate class "frege.imp.builders.FregeBuilder".
    org.eclipse.ui.internal.registry.FileEditorMapping.setDefaultEditor(Lorg/eclipse/ui/internal/registry/EditorDescriptor;)V

**Comment by Ingo60** [comment]
I'm not sure what you were doing.

I just updated frege.ide_3.22.367.b to frege.ide_3.23.343.a on Eclipse Kepler.
After restart, removal of the old fregec.jar from build path and re enabling the Frege Builder, I cleaned the project and the rebuild works fine, as expected.

I recommend the following:

  * uninstall frege.ide from eclipes 
  * find the plugins/ directory, remove all frege.ide_*/ subdirectories that are there
  * install frege.ide again
  * make sure to remove the old fregec.jar from the build path and then "Enable Frege Builder" from the project context menu.

Here is a dirty little secret that might save you some work in the future: Just download the fregec.jar from releases or build your own from HEAD and replace the one in plugins/frege.ide*/lib with it. Only if this doesn't work do you really need to do the upgrade procedure.

The 24 is, of course a typo. Sorry. But it is only in the description, AFAICS.

**Comment by muhuk** [comment]
Reinstalling the plugin failed:

    An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
    session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
    Error reading signed content.
    /home/muhuk/lib/eclipse/plugins/frege.ide_3.23.343.a (No such file or directory)

Perhaps deleting the directory was not such a good idea.

**Comment by Ingo60** [comment]
You did uninstall it before, did you?

Never mind, I can send you a tar file to recreate it. Just tell me where.

**Comment by muhuk** [comment]
Now I'm getting this error:

    Errors occurred during the build.
    Error instantiating builder 'frege.ide.frege.builder'.
    Plug-in "frege.ide" was unable to instantiate class "frege.imp.builders.FregeBuilder".
    Could not initialize class frege.imp.builders.FregeBuilder
    Plug-in "frege.ide" was unable to instantiate class "frege.imp.builders.FregeBuilder".
    Could not initialize class frege.imp.builders.FregeBuilder

**Comment by muhuk** [comment]
...and I'm still getting the first error, when I disable auto-build, clean and then try building.

**Comment by Ingo60** [comment]
This is the same you got before?
How is this? Clearly, that class is there?

    ingo@delluntu:~/eclipse/kepler/plugins/frege.ide_3.23.343.a$ ls -l frege/imp/builders 
    total 52
    -rw-rw-r-- 1 ingo ingo  1894 Okt  9 18:40 FregeBuilder$1CompProgress.class
    -rw-rw-r-- 1 ingo ingo  1656 Okt  9 18:40 FregeBuilderBase$AllSourcesVisitor.class
    -rw-rw-r-- 1 ingo ingo 12862 Okt  9 18:40 FregeBuilderBase.class
    -rw-rw-r-- 1 ingo ingo  1128 Okt  9 18:40 FregeBuilderBase$SourceCollectorVisitor.class
    -rw-rw-r-- 1 ingo ingo  1248 Okt  9 18:40 FregeBuilderBase$SourceDeltaVisitor.class
    -rw-rw-r-- 1 ingo ingo 12791 Okt  9 18:40 FregeBuilder.class
    -rw-rw-r-- 1 ingo ingo   950 Okt  9 18:40 FregeNature.class

**Comment by muhuk** [comment]
Yes, I got same files.

**Comment by tliron** [comment]
I am having the exact same problem. Using Eclipse Mars over JDK8.

    Errors occurred during the build.
    Error instantiating builder 'frege.ide.frege.builder'.
    Plug-in "frege.ide" was unable to instantiate class "frege.imp.builders.FregeBuilder".
    org.eclipse.ui.internal.registry.FileEditorMapping.setDefaultEditor(Lorg/eclipse/ui/internal/registry   /EditorDescriptor;)V

**Comment by Ingo60** [comment]
@tliron Windows or Linux?

**Comment by Ingo60** [comment]
Yep. Here is the stacktrace:

    java.lang.NoSuchMethodError: org.eclipse.ui.internal.registry.FileEditorMapping.setDefaultEditor(Lorg/eclipse/ui/internal/registry/EditorDescriptor;)V
	at org.eclipse.imp.language.LanguageRegistry.addUniversalEditorMappings(LanguageRegistry.java:393)
	at org.eclipse.imp.language.LanguageRegistry.initializeRegistryAsNeeded(LanguageRegistry.java:268)
	at org.eclipse.imp.language.LanguageRegistry.findLanguage(LanguageRegistry.java:206)

This means nothing less that eclipse changed the API.
Did you notice that the upgrade did download some stuff before actually downloading frege.ide, and that afterwards you suddenly had MARS.1?

We will have to warn people not to upgrade the plugin with MARS.
Also, I guess, any upgrade that causes MARS.1 to get installed will cause the frege.ide to fail.

**Comment by Ingo60** [comment]
Confirmed this by "Check for Upgrades", it found Eclipse 4.5.1 and frege.ide, but I did upgrade only the former.
This caused the same error after restart. The missing method is

    org.eclipse.ui.internal.registry.FileEditorMapping.setDefaultEditor(Lorg/eclipse/ui/internal/registry/EditorDescriptor;)V

but, of course, we have no clue what else is missing or has changed.

**Comment by Ingo60** [comment]
Asked a question on SO http://stackoverflow.com/questions/33111344/eclipse-4-5-1-mars-1-method-not-found-setdefaulteditor

**Comment by tliron** [comment]
@Ingo60 Linux. (Ubuntu 14.04 AMD64.) Would happy to run any tests you need to help debug this!

**Comment by Ingo60** [comment]
@tliron Thank you! Unfortunately, it seems that the IMP framework that I was using for the Frege IDE is calling an "Internal" eclipse method, and for some reason they choose to remove or alter it in 4.5.1.

So I'm afraid we can't do anything here, as I don't have the knowledge to hack the IMP sources. (If they are available anyway.)

I think we need a new IDE, or at least a new plugin, or we're forever stuck with LUNA.

This is not so bad at this time, but will get worse from year to year, I guess.

**Comment by tliron** [comment]
Thanks for the explanation. Well, I hope someone can pick up the glove and rewrite the fregIDE to use modern Eclipse technology. The lack of up-to-date integration with Eclipse will unfortunately hurt the adoption rate of Frege.

**Comment by Ingo60** [comment]
It looks like there is a fix for IMP. Will try to get it included, but can do this only next weekend. 

So, stay tuned.

**Comment by tliron** [comment]
Sounds great!
For now, I have been able to be productive in Eclipse using the Frege Gradle Plugin.
(By the way, I've created a [minimal example](https://github.com/tliron/frege-gradle-plugin-example) for using it with Eclipse.)

**Comment by Ingo60** [comment]
Hi, I think I could fix it by switching to "Impulse", which is a successor for "IMP".

@muhuk @tliron Could you try out the recipe in https://github.com/Frege/eclipse-plugin/wiki/Transition-to-frege.ide-with-Impuls-plugin

I checked it in Kepler, Luna and MARS.1, and it does work for me.

**Comment by muhuk** [comment]
In case you miss it in the chat:

    [22:12] <muhuk> @Ingo60: I'm currently trying the migrations guide.
    [22:12] <muhuk> This is I did and it didn't end well for me: " Stop Eclipse and remove left-overs in plugins/ directory"
    [22:12] <muhuk> So I would suggest removing that.
    [22:18] <muhuk> What is "Impuls feature". I'm googling but can't find anything on it.

**Comment by Ingo60** [comment]
What happened, @muhuk ?

https://github.com/usethesource/impulse is the successor of the IMP framework we formerly used. It gets maintained and modernized, or so it seems.

**Comment by muhuk** [comment]
I don't remember the exact error. But one thing is those dirs/files are listed in `artifacts.xml` and I had to clean it up to make eclipse work again.

**Comment by tliron** [comment]
Works for me with latest update!
