### ISSUE TITLE
Cannot install fregIDE

### ISSUE THREAD

**Issue by KoenOlaerts** [Frege/eclipse-plugin#17]
Hello,

I'm trying to install fregIDE into the new Eclipse Mars but am not successful. During the installation progress a problem occurs, stating some frege artifacts cannot be found. This also occurs with alternative URL.
I downloaded the latest MARS.1 version so it is a clean package. 

I also tried installing fregIDE into a fresh Eclipse Luna and an older Kepler but with the same results. 

I am working on a Macbook Pro with OS X El Capitan.

If I only select the Frege IDE Support feature, as described in the installation tutorial, the installation runs successfully. 
> In the list box expand the feature Frege IDE Support and select the latest version of Frege Development

It seems strange to me that there are also other features not required. With just this one feature selected, do I have full development possibilities?

<img width="659" alt="artifactsnotfound" src="https://cloud.githubusercontent.com/assets/2323549/10563395/d2574c2c-7588-11e5-99cd-976fe8730f28.png">

**Comment by Ingo60** [comment]
If you install some feature from an eclipse update site it will pull in the dependend features and plugins from that site and even different sites you have configured. Hence you should be fully functional.

An eclipse update site can host multiple products, features, plugins etc. So, if you want A then install just A and ignore the rest.

As this apparently causes confusion, I removed the "Impulse Feature". 

BTW, yesterday we had an important patch concerning Haskell source compatibility. So you may want to try it out again and install 3.23.370 (or just replace the fregec.jar)

**Comment by KoenOlaerts** [comment]
Thanks for the info.
I also upgraded to the new version.
