### ISSUE TITLE
Workspace error after updating the plugin to v3.23.472.a

### ISSUE THREAD

**Issue by muhuk** [Frege/eclipse-plugin#20]
I'm getting this error when I try to build:

    Errors occurred during the build.
    Errors running builder 'Frege builder' on project 'frege-edn'.
    frege/runtime/Value : Unsupported major.minor version 52.0

This is the installed plugin:

    Frege Development	3.23.472.a	frege.feature.feature.group	Ingo Wechsung

I had manually removed the old jar, re-enabled the builder and can confirm the new jar is in _Referenced Libraries_.

**Comment by Ingo60** [comment]
It works only with java8.
Please use the next lower one, should be 401, or some such.

**Comment by Ingo60** [comment]
I have updated the tutorial, where it previously said, that you should use the ones under Frege IDE category. 
I have now added that no, you shouldn't use anything from another category.
