### ISSUE TITLE
Frege/frege Maybe compilation Error 

### ISSUE THREAD

**Issue by jwausle** [Frege/eclipse-plugin#21]
Line43: protected package frege.prelude.Maybe
Line44:        inline (Maybe.Maybe.>>=, Maybe.Maybe.>>, Maybe.Maybe.return, Maybe.Maybe.<*>) 
Line45:    where

Multiple messages at this line.
    -Java compiler errors are almost always caused by bad native declarations. When you're sure this is 
     out of the question you've found a compiler bug, please report under https://github.com/frege/frege/issues 
     and attach a copy of /Users/winter/Git/frege-root/bin/frege/prelude/Maybe.java
    -$constƒ5f186b3d cannot be resolved or is not a field
    -$constƒ5f186b3d cannot be resolved or is not a field
    -$constƒ5f186b3d cannot be resolved or is not a field

System:
-     MacOS (Yosomite): 10.10.1
-     Java-JDK:                1.8.0_31
-     Eclipse (Luna):         4.4.0
-     Frege-Plugin:           3.23.472.a
-     .project, .classpath, .settings are zipped+attached
  [eclipse-project-files.zip](https://github.com/Frege/eclipse-plugin/files/68316/eclipse-project-files.zip)

**Comment by jwausle** [comment]
make fregec.jar (build succ)

**Comment by Ingo60** [comment]
Looks like you're compiling the compiler in Eclipse.

Did you follow https://github.com/Frege/eclipse-plugin/wiki/Working-on-the-compiler-with-Eclipse-(and-Frege-plugin) ?
