### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by mohanr** [Frege/eclipse-plugin#23]
I added sslVerify=false to my eclipse Git configuration but it may not be the right place.

Unable to read repository at https://raw.githubusercontent.com/Frege/frege.github.com/master/fregide/content.xml.
Unable to read repository at https://raw.githubusercontent.com/Frege/frege.github.com/master/fregide/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

The other repo. fails too.

Unable to read repository at http://www.frege-lang.org/fregide/.
Unable to read repository at http://www.frege-lang.org/fregide/.
http://www.frege-lang.org/fregide/ is not a valid repository location.

**Comment by Ingo60** [comment]
Never seen this before.
Which eclipse version are you using?

**Comment by mohanr** [comment]
Eclipse Mars.

**Comment by mohanr** [comment]
The PKIX issue vanished when I tried from home with no corporate proxy. Unsure about the reason.

**Comment by Ingo60** [comment]
I'm happy to hear this. So I guess we can conclude that there is a problem with certain weird network setup/firewalls/content filters as they are common in corporate networks.

Also, thank you for reporting, this may help someone else later.

**Comment by mohanr** [comment]
Yes. The proxy was the difference. The plugin URI is a git URI. So in such cases the  PKIX problem  is generally solved by setting ssl verification to 'false'.  That is what I believe based on my experience with other package managers like 'npm'. But here the 'http.sslVerify' setting is for eclipse git. So it doesn't seem to take effect.
