### ISSUE TITLE
Frege within OSGi bundle

### ISSUE THREAD

**Issue by ronslow** [Frege/eclipse-plugin#25]
Hi

Is it possible to create a new Eclipse plug in project, enable the Frege builder, write a Frege file and then call the Frege class from within the Activator?

I have a Frege file

`module rojat.fregtestosgi.FregTest where`

`main :: IO ()`
`main = putStrLn "Hello world"``

I have an activator which has the start() method
`public void start(BundleContext bundleContext) throws Exception {`

`		Activator.context = bundleContext;`
`		rojat.fregtestosgi.FregTest.main();`
`	}`

I have the Frege builder running before the Java builder
The FregTest.class files are generated in the bin directory
But the java compiler for Activator is not picking up the generated FreqTest class. I get a compile error that FreqTest is not found. The Java IDE can't see the FreqTest class either.

Is there further configuration I can do to solve this?

Thanks

Robert

**Comment by Ingo60** [comment]
When we have two Frege modules A and B and A imports B, then actually B's class file gets loaded from the bin/ directory. So it is not that Eclipse didn't recognize the class files.

However, it is possible that the JDT doesn't "see" it for some reason. I also experienced that the Navigator view frequently doesn't  show the state of the bin/ directory correctly and must be refreshed to get an actual view.

Can you try to refresh the bin/ after having compiled the Frege file, it should show your class file and I guess only then will the JDT pick it up.

**Comment by ronslow** [comment]
Yup. Refresh worked. Thanks.

**Comment by Ingo60** [comment]
I wish I knew how to announce arrival of a new class file to the JDT, apparently JDT thinks it is the only one that produces them.
