### ISSUE TITLE
Unable to install eclipse plugin

### ISSUE THREAD

**Issue by stillalex** [Frege/eclipse-plugin#33]
I'm trying to install the eclipse plugin and it fails. I'm following the tutorial here [0] and have tried both urls with the same error.

I setup the update site, I see Frege Development 3.24.409, select, click Finish and get the following:
```
An error occurred while collecting items to be installed
session context was:(profile=_Users_aparvule_java_eclipse_java-oxygen_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://www.frege-lang.org/fregide/plugins/impulse_0.1.0.201804202307.jar.
http://www.frege-lang.org/fregide/plugins/impulse_0.1.0.201804202307.jar
```

Eclipse IDE:
```
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
```

any help is appreciated!

[0] https://github.com/Frege/eclipse-plugin/wiki/fregIDE-Tutorial

**Comment by Ingo60** [comment]
Well, this did go better than anticipated.
Please try again, and let me know if it was ok.

**Comment by stillalex** [comment]
works perfectly! thanks a lot!
moving on to the examples now :)

just for completeness I now see a warning about unsigned content, but don't think it's a big issue
<img width="532" alt="warning" src="https://user-images.githubusercontent.com/61026/39567346-0901132c-4ebf-11e8-9812-07c7c2c3e2a2.png">

**Comment by Ingo60** [comment]
Well, this disturbs me all the time. Luckily, I can trust myself most of the time, while you'll have to take my word for now. 

I hope someday a white knight appears and figures out how signing eclipse artifacts works, and implements it also.
