### ISSUE TITLE
Download Link Problems

### ISSUE THREAD

**Issue by decapo01** [Frege/eclipse-plugin#36]
Both of the download links for the IDE don't seem to be working.  

http://www.frege-lang.org/fregide/ goes to a page that says
```
There is nothing to see here! This is a Eclipse Update Site and not intended for human readers.
```
and the alternate link just goes to a 404 page

**Comment by Ingo60** [comment]
The link is intended for eclipse, not for humans. See the "Installation" paragraph in the tutorial https://github.com/Frege/eclipse-plugin/wiki/fregIDE-Tutorial

**Comment by decapo01** [comment]
Thanks, I totally missed the 
```
Please also read the tutorial that describes the installation in detail.
```
Part of the readme
