### ISSUE TITLE
Provide a Frege type

### ISSUE THREAD

**Issue by przytads** [Frege/eclipse-plugin#9]
Instead of using the text file type, the plugin should provide a Frege type.

**Comment by Ingo60** [comment]
I am not sure I understand what you're talking about? What text file?

**Comment by przytads** [comment]
![screen shot 2015-05-01 at 10 27 49](https://cloud.githubusercontent.com/assets/3452478/7428223/d31bae40-efec-11e4-9eec-2e995aab7240.png)

**Comment by Ingo60** [comment]
This is not from the frege-plugin. Must be some eclipse functionality.

2015-05-01 10:28 GMT+02:00 przytads <notifications@github.com>:

**Comment by Ingo60** [comment]
Based on our chat conversation, this is apparently a request for better integration of the frege plugin in the eclipse ecosystem. For example, you want an action like "New Frege Module" (not Frege Type!).

However, the current plugin is based on the IMP framework, which meanwhile is not maintained anymore. I've put my best efforts into utilizing all functionality that framework offers, but there will not be further developments (except bug fixes or adaptions) for that code base.

That is why there is Issue#1 that asks for support to write a genuine eclipse plugin.
